services:
  # REST API service
  api:
    image: "api:${TAG}"
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    command: air
    expose:
      - "${API_PORT}"
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - qlik
    volumes:
      - ./:/api
    restart: unless-stopped

  # Postgres service
  postgres:
    image: postgres:alpine
    networks:
      - qlik
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"
      POSTGRES_DB: "${DATABASE_NAME}"
    expose:
      - "${DATABASE_PORT}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - pg-data:/var/lib/postgresql/data
    command: -p ${DATABASE_PORT}
    healthcheck:
      test: pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  qlik:

volumes:
  pg-data: