### Users - LIST
GET http://localhost:8080/api/v1/users

### Messages - LIST
GET http://localhost:8080/api/v1/messages

### CREATE
POST http://localhost:8080/api/v1/messages/ffc44559-044d-4525-ae8a-4bd37f2a3d7a
Accept: application/json

{
    "message": "notpalindrome"
}

### UPDATE
POST http://localhost:8080/api/v1/messages/268f7cbb-b719-4d5f-b8d3-c03d985b768c/2024-06-03T22:38:31.313174Z/update
Accept: application/json

{
    "message": "okayyes",
    "last_updated_date": "2024-06-03T22:38:31.313174Z"
}

### DELETE
POST http://localhost:8080/api/v1/messages/268f7cbb-b719-4d5f-b8d3-c03d985b768c/2024-06-03T22:38:31.313174Z/delete
Accept: application/json

{
    "last_updated_date": "2024-06-03T22:38:31.313174Z"
}